export { default as airbnb } from './airbnb.svg';
export { default as facebook } from './facebook.svg';
export { default as google } from './google.svg';
export { default as graph1 } from './graph1.png';
export { default as graph2 } from './graph2.png';
export { default as hubspot } from './hubspot.svg';
export { default as slack } from './slack.svg';
export { default as background } from './background.svg';
export { default as desk_background } from './desk_background.svg';
